default_platform(:ios)

platform :ios do
  before_all do
    setup_circle_ci
  end

  ########################################################################
  # Adhoc Lane
  ########################################################################
  desc "Ad-hoc build"
  lane :adhoc do |options|
    ########################
    # Pull certs & profiles
    ########################
    sync_code_signing(type: "adhoc")

    ########################
    # Build the app
    ########################
    increment_build_number(build_number: options[:build_number])

    # Make sure and set either GYM_WORKSPACE or GYM_PROJECT and GYM_SCHEME
    build_ios_app(
      export_method: "ad-hoc",
      include_bitcode: true,
      skip_profile_detection: true
    )

    ########################
    # Upload to App Center
    ########################
    distribute = options[:distribute].to_s != 'false'


    if distribute
      appcenter_upload(
        ipa: "./#{ENV['GYM_OUTPUT_NAME']}.ipa",
        dsym: "./#{ENV['GYM_OUTPUT_NAME']}.app.dSYM.zip"
      )

      if ENV['SLACK_URL']
        group = ENV['APPCENTER_DISTRIBUTE_GROUP'] || 'Collaborators'
        slack(message: "Successfully distributed *iOS* build *#{options[:build_number]}* to the *#{group}* group on App Center")
      end
    end
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
